version: "3.3"

services:
  aroma:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/workspace
      - ./docker/database.yml:/workspace/config/database.yml
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:11.6
    environment:
      POSTGRES_USER: "aroma"
      POSTGRES_PASSWORD: "aroma"
      POSTGRES_DB: "aroma_main"
    ports:
      - "5433:5433"
  redis:
    image: redis:latest
