my_first_job:
  cron: "0 */12 * * *" 
  class: "FetchAllOrdersAndSubscriptionBulkWorker"

my_second_job:
  cron: "0 1 * * *" 
  class: "UpdateUsageChargesWorker"

my_third_job:
  cron: "0 0 * * *"
  class: "CreateRebuyForAllCustomersWorker"
