name: shopapp Docker Image CI

on:
  push:
    branches: [ main-production ]

jobs:

  build:
    env:
      MSG: ${{ github.event.head_commit.message }}
      AUTHOR: ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main-production
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag codilitymohsin/shopapp:release
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push to Dockerhub
      run: docker push codilitymohsin/shopapp:release
    - name: Cleanup
      run: docker image prune -f
