name: Chargezen Test
on:
  push:
    branches: 'db_rework'
jobs:
  push_event:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/chargezen/Chargezen
<<<<<<< HEAD
          git reset --hard
          git pull origin db_rework
          rails db:migrate
          yarn install --check-files
=======
          git pull origin db_rework
          rails db:migrate
          yarn install --check-files
          sudo kill -9 `sudo lsof -t -i:3000`
>>>>>>> 96710a6f5f4b808c9d561c49c5932e47cdfd0b9b
          rails s -d
